# Generated by Django 4.2.7 on 2023-12-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('image', models.ImageField(upload_to='productos', verbose_name='Imagen')),
                ('product1', models.CharField(max_length=100, verbose_name='Producto1')),
                ('product2', models.CharField(max_length=100, verbose_name='Producto2')),
                ('product3', models.CharField(max_length=100, verbose_name='Producto3')),
                ('product4', models.CharField(max_length=100, verbose_name='Producto4')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha modificación')),
            ],
            options={
                'verbose_name': 'Promo',
                'verbose_name_plural': 'Promos',
                'ordering': ['created'],
            },
        ),
    ]
